---
title: "stair-design-principles"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{stair-design-principles}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Stair design principles

## Historical background

**Historical Approach.** The classical stair-design relationship is commonly expressed as "the Blondel value":

$$
2R + G \approx L
$$

where `R` is the rise and `G` is the going. Originally, Blondel introduce^["Blondel probably referred to the French (pre-Revolutionary) royal inch" (Templer, 1992, p. 27).] an ideal value of 64.77 cm (Templer, 1992, p. 27). 

**Modern Approach.** Therefore, modern approach should enlarge the theoritical value given by Blondel: 

> If we adjust for the pace of people today, depending on leg length and walking speed—say, 28 inches (71 cm) - and express the formula in today's measures, then it would become: 

$$
2R + G \approx 71\ cm
$$

> Templer, John A. The Staircase: Studies of Hazards, Falls, and Safer Design. 2. print. *MIT Press*, 1992. https://doi.org/10.7551/mitpress/6434.001.0001. p. 27

**Actual practices.** To the best of our knowledges, actual masonry and carpentry guidelines introduce the ideal value at 63 cm, with acceptable range of solution between 60 cm to 64 cm (e.g., ici ref compagnons du devoir). Cela est en accord avec les anciennes réglementations, p. ex. regarding old French legal guidelines, rise have to be comprise between 13 cm and 17 cm, the going have to be comprise between 28 cm and 36 cm, and "hauteur et largeur seront liées par la relation" 0,60 m ≤ 2H + G ≤ 0,64 (https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000441635/2024-04-22 - Arrêté From the 23 mars 1965 - article CO 66).
 
Thus,

$$
60≤2R+G≤64\ cm
$$

**Anciennes règles Françaises : Escalier hors les normes si giron inférieur à 28 cm. Hauteur maximale de 17 cm.**

**Modern Approach.** Pour les ERP neufs et installations ouvertes au public aménagées, l'arrêté du 20 avril 2017, article 7-1, fixe une hauteur de marche maximale (?) de 16 cm et un giron minimal de 28 cm (https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000034485956). L'arrêté du 24 décembre 2015, article 6 / annexe 6.1, prévoit pour les escaliers des parties communes une hauteur maximale (?) de 17 cm et un giron minimal de 28 cm (https://www.legifrance.gouv.fr/loda/id/JORFTEXT000031692481/).


**Accessing Machineries.** Regarding industrial ISO standards for accessing a machinery, the acceptable values are between 58 cm and 66 cm (ISO 14122-3:2016, NF EN ISO 14122-3:2017).  

La hauteur maximum de marche est de 21 cm et le giron minimal de 19 cm (EN ISO 14122-3:2016, Safety of machinery - Permanent means of access to machinery - Part 3: Stairs, stepladders and guard-rails^[French equivalent to EN ISO 14122-3:2016 is NF EN ISO 14122-3:2017.]). Idéalement, le giron doit être compris entre 21 cm et 31 cm.


**REGLES ISO Machinery : Escalier hors-les-normes : giron inférieur a 19 cm. Hauteur maximum de 21 cm.**


**Stair comfort.** Pour le DTU français, il y a 3 classes de confort d'escaliers:

1. Raide 1.32 > H/G > 1
2. Courant 1 > H/G > 0.78
3. Confortable H/G < 0.78

Avec H hauteur de marche et G Giron.

*Ici pente en degrés !*


**Experimental Research.**

Experimental research has subsequently investigated stair dimensions
using several criteria, including energy expenditure, biomechanical
constraints, perceived difficulty and fall risk. 

> A reasonable compromise would be a stair with risers
that are not less than 6.3 inches (16 cm) to suit ascent, and risers not more than 7.2 inches (18.3 cm) and goings greater than 9 inches (22.9 cm) to suit descent (Templer, 1992, p. 39).

> • In terms of gait, risers should be 6.3 to 7.2 inches (16-18.3 cm) and goings should not be less than 9 inches (22.9 cm).
> 
> • The etiological studies suggest that risers should not exceed 7.5 inches (19.1 cm) and goings should not be less than 9 inches (22.9 cm).
> 
> • To accommodate feet adequately, goings should not be less than 11 inches (27.9 cm).
> 
> Templer, John A. The Staircase: Studies of Hazards, Falls, and Safer Design. 2. print. *MIT Press*, 1992. https://doi.org/10.7551/mitpress/6434.001.0001. p. 38


## Ergonomic research

Theoritical lab' values : 
cm 
Rise Goings
18.3 27.9
17.8 27.9
16.5 27.9 29.2 30.5 31.8
15.2 27.9 29.2 30.5 31.8 33.0 34.3 35.6
14.0 27.9 29.2 30.5 31.8 33.0
12.7 27.9 29.2 30.5
11.7 27.9

p. 39

