#' Build the complete table of stair solutions (embedded geometry)
#'
#' Computes one summary row for each valid number of steps and each going
#' scenario generated by \code{\link{generate_going_scenarios}}. Each row
#' includes the complete stair geometry, generated with
#' \code{\link{build_geometry}}, as a list-column named \code{geometry}.
#'
#' The geometry associated with a solution
#' can be accessed directly with \code{solution$geometry[[1]]}.
#'
#' @param candidates A `data.frame` returned by
#'   \code{\link{optimal_nrisers}}.
#' @param max_horizontal_run Maximum available horizontal run (cm).
#' @param blondel_target Target value for Blondel's formula
#'   \code{2 * rise + going} (cm). Default is 63.
#'
#' @return Return a \code{data.frame} (with additional class
#'   \code{stair_solutions}) containing one row per combination of
#'   number of steps and going scenario. The returned data frame includes
#'   the following columns:
#'   \itemize{
#'     \item \code{n_risers}: Number of steps to climb.
#'     \item \code{step_rise}: Step height (rise).
#'     \item \code{rise_target_deviation}: Deviation from the target step height.
#'     \item \code{going}: Standard going.
#'     \item \code{scenario}: Name of the going scenario.
#'     \item \code{horizontal_run}: Total horizontal run.
#'     \item \code{blondel}: Value of Blondel's formula (\eqn{2h + g}).
#'     \item \code{blondel_target_deviation}: Deviation from the Blondel target.
#'     \item \code{has_landing}: Whether the solution includes a landing.
#'     \item \code{horizontal_run_exceeded}: Whether the available horizontal run is exceeded.
#'     \item \code{landing_impossible}: Whether a landing is required but impossible.
#'     \item \code{is_valid}: Whether the solution satisfies all design rules.
#'     \item \code{geometry}: A list-column containing the complete stair geometry
#'       as a `data.frame`.
#'   }
#' @examples
#' candidates <- optimal_nrisers(160)
#' tbl <- build_solutions_table(candidates, max_horizontal_run = 1000)
#' head(tbl)
#' plot(tbl$geometry[[1]])
#'
#' @export
build_solutions_table <- function(candidates, max_horizontal_run, blondel_target = 63) {

  lines_per_candidate <- lapply(seq_len(nrow(candidates)), function(i) {

    n_risers <- candidates$n_risers[i]
    step_rise <- candidates$rise [i]
    rise_target_deviation <- candidates$rise_target_deviation[i]
    standard_going <- blondel_going(step_rise, blondel_target)

    scenarios <- generate_going_scenarios(n_risers, max_horizontal_run, standard_going)

    lignes <- lapply(names(scenarios), function(name_scenario) {
      sc <- scenarios[[name_scenario]]
      geometry <- build_geometry(n_risers, step_rise, sc$goings)

      data.frame(
        n_risers            = n_risers,
        step_rise       = step_rise,
        rise_target_deviation = rise_target_deviation,
        going       = standard_going,
        scenario             = name_scenario,
        horizontal_run    = sc$horizontal_run,
        blondel       = (2 * step_rise) + sc$goings[[1]],
        blondel_target_deviation        = sc$blondel_target_deviation,
        has_landing         = isTRUE(sc$has_landing),
        horizontal_run_exceeded       = isTRUE(sc$horizontal_run_exceeded),
        landing_impossible    = isTRUE(sc$landing_impossible),
        geometry            = I(list(geometry)),
        stringsAsFactors     = FALSE
      )
    })

    do.call(rbind, lignes)
  })

  res <- do.call(rbind, lines_per_candidate)

  # a valid solution fit in length & don't have a landing step OR there is a possible landing step
  res$is_valid <- !res$horizontal_run_exceeded & (res$has_landing == FALSE | (res$has_landing == TRUE & !res$landing_impossible))

  rownames(res) <- NULL

  res <- structure(res,  "n_valid_solution" = length(which(res$is_valid) ) ) 
  
  class(res) <- c("escalier_solutions", class(res))
  
  return(res)
  
}

#' Print stair solutions without the geometry list-column
#'
#' The \code{geometry} column contains complete geometry data frames.
#' Displaying it directly would make the output difficult to read.
#' This print method hides the \code{geometry} column while keeping it
#' fully accessible through \code{$geometry}.
#'
#' @param x A \code{stair_solutions} object.
#' @param ... Additional arguments passed to
#'   \code{print.data.frame()}.
#'
#' @export
print.escalier_solutions <- function(x, ...) {

  n_valid_solutions <- integer(0)
  n_valid_solutions <- if("is_valid" %in% names(x)) length(which(x$is_valid) )
  if(length(n_valid_solutions) > 0) cat("\n ",n_valid_solutions , "valid solution(s)\n") 
  
  print.data.frame(x[, setdiff(names(x), "geometry")], ...)
  
  cat("('geometry' list-col is hidden - access via $geometry[[i]])\n")
  invisible(x)
}
